# This is a multi-package Cabal project with no root .cabal file, so the
# single-package callCabal2nix output generated by nix/haskell.nix is invalid.
{ lib, ... }:
{
  perSystem = { pkgs, ... }: {
    packages = lib.mkForce { };

    # git must come from nixpkgs, not from macOS. `/usr/bin/git` is an Xcode
    # Command Line Tools shim that resolves normally but fails to *execute*
    # inside `nix develop` with "error: tool 'git' not found" — the shim needs
    # developer-directory state that the shell's environment does not carry.
    # An interactive `nix develop` hides this, because the shim happens to work
    # when the surrounding login shell has already been through xcrun. The mori
    # automation daemon has not: it runs reactions as
    # `nix develop --command …` under launchd with a minimal PATH, where every
    # git call in scripts/upgrade-baikai.sh fails and the branch it reads comes
    # back empty. See docs/user/automated-baikai-upgrades.md.
    haskellProject.extraDevPackages = [ pkgs.git ];

    checks.haskell-conventions = pkgs.runCommand "kioku-haskell-conventions"
      {
        nativeBuildInputs = [ pkgs.bash pkgs.gnugrep pkgs.ripgrep ];
      } ''
      cd ${./.}
      bash scripts/check-haskell-conventions.sh
      touch $out
    '';

    pre-commit.settings.hooks.haskell-conventions = {
      enable = true;
      name = "Haskell conventions";
      entry = "${pkgs.bash}/bin/bash scripts/check-haskell-conventions.sh";
      pass_filenames = false;
    };
  };
}
