# This is a multi-package Cabal project with no root .cabal file, so the
# single-package callCabal2nix output generated by nix/haskell.nix is invalid.
{ lib, ... }:
{
  perSystem = { ... }: {
    packages = lib.mkForce { };
  };
}
